language: node_js
node_js:
  - "12"
dist: xenial
sudo: required
cache:
  directories:
    - ~/.npm
    - node_modules
branches:
  only:
  - main
before_script:
  - npm install
script:
- npm run lint
- npm run e2e:ci --record --key $CYPRESS_RECORD_KEY
- npm run build:prod
addons:
  chrome: stable
notifications:
  slack: $SLACK_ACCOUNT:$SLACK_TOKEN