language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
cache:
  directories:
    - ~/.npm
    - node_modules
branches:
  only:
  - main
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- npm run e2e:ci --record --key $CYPRESS_RECORD_KEY
- ng build --prod
addons:
  chrome: stable
notifications:
  slack: $SLACK_ACCOUNT:$SLACK_TOKEN