language: node_js
node_js:
  - 12
dist: xenial
install:
  - npm ci
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
cache:
  directories:
    - "$HOME/.npm"
    - node_modules
git:
  depth: false
  quiet: true
  submodules: false
branches:
  only:
    - main
    - staging
script:
  - if [ "$TRAVIS_BRANCH" = "main" ]; then npm run lint; fi || travis_terminate 1;
  - if [ "$TRAVIS_BRANCH" = "main" ]; then npm run e2e:ci -- --key $CYPRESS_RECORD_KEY; fi || travis_terminate 1;
  - if [ "$TRAVIS_BRANCH" = "main" ]; then npm run codecov; fi || travis_terminate 1;
  - npm run build:prod || travis_terminate 1;
addons:
  chrome: stable
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET_NAME
  region: $AWS_DEFAULT_REGION
  cleanup: true
  local_dir: dist/datariomj/browser
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  slack:
    secure: 03rf2r8vBDsOf/u/Hh2Mtyk4uQIEvxVBR+xNNToAiPQnGgzh1zX/1dvXqOPvnWAuJTYCkYMfGydHfN10yq4h/n8Bs1hNqrKPHbAfEAudLEYpQyVP3F2AgqKfrSVdGwTl5x53qFHCXQISBHc8uXGapbGKILjc8TZLUDIPV5DjNHJY4lzrFS2D0BrOcgGptj0gvb5v5vsVep586PVHvm1wwumfdy23ttDt8/RTI+DXQzMmDfzH8v5udkiAKDnPkJwTrqqZyaSBDfmZXPfTxU9SgVaxa5WCm/DNHsoDuLL39u1rWblzI36cPg7F5ik+ULr+vTHjHQACWQgMljHgS6xuMiWxNOU27zUCwJOaGwevhHOmJmBEbE4qEXp0Fa9NqFI6EZHmb0U/+hQbaaBpbG/Jr59klr6zzDEnU873gaxN8Y1PrO35GrXgc76wyBotsB3w5sAqFAZNsdPqArNrp+/O9dYYu/iRug4mObcuLKdroKWb323AhZZvWYjJ6Bqt4cpbLmjisPSN/JFZh5u73fs18Gp2qqYZnZk1IA6VgEwnls9teZqs1v7fMZiqiszWe6N9XmqFcZJpy1hRMq55Ud2naxp7oJdIllEWRHA0gGbsJqNt9cZUuTnHhGdPpiKb5cQlLqDk76dJvdhvAVlHM5/X1l4quQKROUtpjCCqxUua+xM=