stages:
  - stage: Init
    jobs:
      - job: SelectNode
        steps:
          - bash: whoami
          - bash: ls ~/
          - bash: nvm use 18
  - stage: Build
    jobs:
      - job: InstallNPMDependencies
        container: node
        steps:
          - script: npm ci
  - stage: Test
    jobs:
      - job: Tests
        steps:
          - script: echo "Run Tests"
  - stage: Publish
    jobs:
      - job: TestJob
        steps:
          - script: echo "Create Artifacts"
  - stage: Deploy
    jobs:
      - job: TestJob
        steps:
          - script: echo "Deploy to S3, CloudFront and invalidate"
  - stage: Post
    jobs:
      - job: Notify
        steps:
          - script: echo "Notify via email"
