stages:
  - stage: Init
    jobs:
      - job: Notify
        steps:
          - script: echo "Notify via email"
  - stage: Build
    jobs:
      - job: InstallDependencies
        steps:
          - script: echo "Install Dependencies"
  - stage: Test
    jobs:
      - job: Tests
        steps:
          - script: echo "Run Tests"
  - stage: Publish
    jobs:
      - job: TestJob
        steps:
          - script: echo "Create Artifacts"
  - stage: Deploy
    jobs:
      - job: TestJob
        steps:
          - script: echo "Deploy to S3, CloudFront and invalidate"
  - stage: Post
    jobs:
      - job: Notify
        steps:
          - script: echo "Notify via email"

