trigger:
  branches:
    include:
      - main
      - staging

pr:
  autoCancel: true
  branches:
    include:
      - snyk-upgrade-*

pool:
  name: Default

stages:
  - stage: Build
    jobs:
      - job: TestJob
        steps:
          - script: echo Building!
# jobs:
#   - job: BuildAndDeploy
#     displayName: "Build and Deploy"
#     steps:
#       - script: npm ci
#         displayName: "Install Dependencies"

#       - script: |
#           if ! [ -x "$(command -v aws)" ]; then
#             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#             unzip awscliv2.zip
#             sudo ./aws/install
#           fi
#         displayName: "Install AWS CLI"

#       - script: npm run lint
#         displayName: "Lint"
#         condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

#       - script: npm run e2e:ci -- --record --key $(CYPRESS_RECORD_KEY)
#         displayName: "End-to-End Tests"
#         condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

#       - script: npm run codecov
#         displayName: "Code Coverage"
#         condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

#       - script: |
#           if [ $(Build.SourceBranch) = 'refs/heads/main' ]; then
#             rm src/robots.txt
#             mv src/robots.prod.txt src/robots.txt
#           fi
#         displayName: "Configure Robots.txt"
#         condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

#       - script: npm run build:prod
#         displayName: "Build for Production"

#       - task: PublishBuildArtifacts@1
#         inputs:
#           pathtoPublish: "dist/datariomj/browser"
#           artifactName: "drop"
#         displayName: "Publish Build Artifacts"

#       - script: |
#           aws configure set preview.cloudfront true
#           aws cloudfront create-invalidation --distribution-id $(CLOUDFRONT_DISTRIBUTION_ID) --paths "/*"
#         displayName: "Configure CloudFront Invalidation"
#         condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
