trigger:
  branches:
    include:
      - main
      - release

pr:
  branches:
    include:
      - main
      - release

variables:
  distPath: dist/datariomj/browser
  artifactName: WebApp
  npm_config_cache: $(Pipeline.Workspace)/.npm
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    environment: prod
    publicUrl: https://datariomj.dev
  ${{ else }}:
    environment: 'staging'
    publicUrl: https://staging.datariomj.dev

stages:
  - stage: Init
    jobs:
      - job: Init
        steps:
          - task: Cache@2
            displayName: Cache npm
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)

          - script: npm ci
            displayName: Run npm ci

  - stage: Lint
    dependsOn: Init
    jobs:
      - job: Lint
        steps:
          - task: Cache@2
            displayName: Cache npm
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)

          - script: npm ci
            displayName: Run npm install
          
          - script: npm run lint
            displayName: Run Angular lints
          
          - script: npm run lint:styles
            displayName: Run style lints

          - script: |
              version=$(npm run changelog:version | tail -n 1 | tr -d '\n')
              echo "##vso[task.setvariable variable=version]$version"
              npm run generate:changelog:release
            env:
              GITHUB_TOKEN: $(GH_TOKEN)
            displayName: Generate Changelog

  - stage: Test
    dependsOn: Init
    jobs:
      - job: Test
        steps:
          - task: Cache@2
            displayName: Cache npm
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)

          - script: npm ci
            displayName: Run npm install
          
          - script: npm run test:coverage
            displayName: Run Unit tests

          - script: npm run codecov:upload
            env:
              CODECOV_API_KEY: $(CODECOV_API_KEY)
              CODECOV_FILE: coverage/datariomj/clover.xml
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), ne(variables['CODECOV_API_KEY'], ''))
            displayName: Upload coverage to Codecov

          # - script: npm run e2e:ci -- --record --key $(CYPRESS_RECORD_KEY)
          - script: npm run e2e:ci
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            displayName: Run E2E tests

  - stage: Build
    dependsOn: Init
    jobs:
      - job: Build
        steps:
          - task: Cache@2
            displayName: Cache npm
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)

          - script: npm ci
            displayName: Run npm install
          
          - script: npm run build:$(environment)
            displayName: Run build

          - publish: $(distPath)
            displayName: Publish Web App
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            artifact: $(artifactName)

  - stage: Deployment
    dependsOn:
      - Lint
      - Test
      - Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/release')))
    jobs:
      - deployment: Deploy
        environment: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "##vso[task.setvariable variable=targetS3BukcetId;issecret=true]$(S3_BUCKET_ID)"
                    echo "##vso[task.setvariable variable=targetCloudfrontDistributionId;issecret=true]$(CLOUDFRONT_DISTRIBUTION_ID)"
                  displayName: 'Add AWS Vars for Prod'
                  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                - script: |
                    echo "##vso[task.setvariable variable=targetS3BukcetId;issecret=true]$(STAGING_S3_BUCKET_ID)"
                    echo "##vso[task.setvariable variable=targetCloudfrontDistributionId;issecret=true]$(STAGING_CLOUDFRONT_DISTRIBUTION_ID)"
                  displayName: 'Add AWS Vars for Staging'
                  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
                - checkout: none
                - download: current
                  artifact: $(artifactName)
                - script: aws s3 sync $(Pipeline.Workspace)/$(artifactName) s3://$(targetS3BukcetId)
                  env:
                    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
                    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
                    AWS_DEFAULT_REGION: $(AWS_REGION)
                  displayName: Upload to S3
                - script: aws cloudfront create-invalidation --distribution-id $(targetCloudfrontDistributionId) --paths '/*'
                  env:
                    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
                    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
                    AWS_DEFAULT_REGION: $(AWS_REGION)
                  displayName: Invalidate CloudFront

  - stage: Publish
    dependsOn:
      - Lint
      - Test
      - Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Publish
        steps:
          - task: Cache@2
            displayName: Cache npm
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)
              
          - script: npm ci
            displayName: Run npm install

          - script: |
              version=$(npm run changelog:version | tail -n 1 | tr -d '\n')
              echo "##vso[task.setvariable variable=version]$version"
              npm run generate:changelog:release
              gh release create $version --title "Release $version" --notes-file CHANGELOG.md
            env:
              GH_TOKEN: $(GH_TOKEN)
            displayName: Create GitHub Release
