/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#6ffbbe",
        "secondary-container": "#3a4a5f",
        "background": "#121316",
        "surface-variant": "#343538",
        "on-background": "#e3e2e6",
        "surface": "#121316",
        "surface-container": "#1f1f23",
        "on-tertiary-fixed": "#410005",
        "outline-variant": "#3c4a42",
        "outline": "#86948a",
        "secondary": "#b7c8e1",
        "error-container": "#93000a",
        "tertiary-container": "#fc7c78",
        "on-secondary-container": "#a9bad3",
        "canvas-deep": "#0d0e11",
        "on-primary-fixed-variant": "#005236",
        "on-tertiary": "#650911",
        "surface-container-highest": "#343538",
        "surface-container-high": "#292a2d",
        "on-primary-fixed": "#002113",
        "on-surface-variant": "#bbcabf",
        "on-secondary-fixed": "#0b1c30",
        "primary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#303034",
        "primary": "#10b981", /* Overridden to match standard text-primary green */
        "border-hairline": "#27272a",
        "text-muted": "#94a3b8",
        "surface-container-lowest": "#0d0e11",
        "tertiary-fixed-dim": "#ffb3af",
        "surface-dim": "#121316",
        "tertiary-fixed": "#ffdad7",
        "text-crisp": "#f8fafc",
        "on-primary-container": "#00422b",
        "primary-container": "#10b981",
        "inverse-primary": "#006c49",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-fixed-variant": "#842225",
        "terminal-green": "#10b981",
        "surface-tint": "#4edea3",
        "on-tertiary-container": "#711419",
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface": "#e3e2e6",
        "on-primary": "#003824",
        "tertiary": "#ffb3af",
        "secondary-fixed": "#d3e4fe",
        "on-error-container": "#ffdad6",
        "on-secondary": "#213145",
        "surface-container-low": "#1b1b1f",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "surface-matte": "#16181d",
        "surface-bright": "#38393c",
        "inverse-surface": "#e3e2e6"
      },
      spacing: {
        "stack-md": "1rem",
        "gutter": "1.5rem",
        "stack-sm": "0.5rem",
        "stack-lg": "2.5rem",
        "section-gap": "5rem",
        "max-width": "48rem"
      },
      fontFamily: {
        "headline-xl": ["JetBrains Mono"],
        "headline-lg": ["JetBrains Mono"],
        "code-snippet": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-md": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
        "headline-lg-mobile": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "jetbrains": ["JetBrains Mono", "monospace"],
        "inter": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.05em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "code-snippet": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
