pipeline {
    agent any

    tools {nodejs "nodejs-12"}

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'npm install'
                sh 'npm run prerender'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                withAWS(region:'ap-southeast-1', credentials:'jenkins-aws') {
                    sh 'aws s3 cp ./dist/datariomj/browser s3://staging.datariomj.dev --recursive'
                    sh 'aws cloudfront create-invalidation --distribution-id E3KAH5F445FJPG --paths "/*"'
                }
            }
        }
    }
}