pipeline {
    agent any

    tools {nodejs "nodejs-12"}

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'npm install'
                sh 'npm run prerender'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh 'aws s3 cp ./dist/datariomj/browser/* s3://staging.datariomj.dev --recursive'
            }
        }
    }
}